name: Dropzilla CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        include:
          - python-version: "3.10"
            runs_on: ubuntu-latest
          - python-version: "3.11"
            runs_on: ubuntu-latest
          - python-version: "3.12"
            runs_on: [self-hosted, gpu]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run static type checking with mypy
      run: |
        mypy . --ignore-missing-imports

    - name: Run tests with pytest
      run: |
        pytest

  verify_gpu:
    strategy:
      matrix:
        os: [ubuntu-latest]
    if: contains(matrix.os, 'ubuntu')
    runs-on: [self-hosted, gpu]
    timeout-minutes: 15
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: pip install -r requirements.txt
    - run: python scripts/verify_gpu.py
